1. Create EBS CSI Plugin IAM role 
2. Add add-on through console 



1. Create EBS CSI Plugin IAM role 
- eksctl create iamserviceaccount \
    --name ebs-csi-controller-sa \
    --namespace kube-system \
    --cluster <my-cluster> \ # CLUSTER_NAME
    --role-name <AmazonEKS_EBS_CSI_DriverRole> \  # OIDC_ROLE_NAME
    --role-only \
    --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
    --approve

- (optional) if you want to use your own kms key for EBS encryption, 
  # create policy json file
  # store it in file with name <kms-key-for-encryption-on-ebs.json> # file name
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "kms:CreateGrant",
          "kms:ListGrants",
          "kms:RevokeGrant"
        ],
        "Resource": ["custom-key-arn"], # custom key arn
        "Condition": {
          "Bool": {
            "kms:GrantIsForAWSResource": "true"
          }
        }
      },
      {
        "Effect": "Allow",
        "Action": [
          "kms:Encrypt",
          "kms:Decrypt",
          "kms:ReEncrypt*",
          "kms:GenerateDataKey*",
          "kms:DescribeKey"
        ],
        "Resource": ["custom-key-arn"] # custom key arn
      }
    ]
  }

  # create policy
  aws iam create-policy \
  --policy-name KMS_Key_For_Encryption_On_EBS_Policy \ # policy name
  --policy-document file://kms-key-for-encryption-on-ebs.json # json file name

  # attach policy to role
  aws iam attach-role-policy \
  --policy-arn arn:aws:iam::111122223333:policy/KMS_Key_For_Encryption_On_EBS_Policy \ # above mentioned policy name
  --role-name AmazonEKS_EBS_CSI_DriverRole # above created role

2. Add EBS csi driver add-on using the aws management console. 
  # Edit the role of the EBS csi driver add on. 

